GET http://localhost.chexo.resolved.cl/api/stock/notificacion/notificarsap HTTP/1.1

content-type: application/json
{
}

###
GET http://localhost.chexo.resolved.cl/api/stock/notificacion/notificarsiga HTTP/1.1

content-type: application/json
{
}