-- MySQL Script generated by MySQL Workbench
-- Thu Jan 11 16:14:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Autogestores_Warehouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Autogestores_Warehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Autogestores_Warehouse` DEFAULT CHARACTER SET utf8 ;
USE `Autogestores_Warehouse` ;

-- -----------------------------------------------------
-- Table `Autogestores_Warehouse`.`Region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autogestores_Warehouse`.`Region` (
  `IdRegion` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`IdRegion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autogestores_Warehouse`.`Comuna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autogestores_Warehouse`.`Comuna` (
  `IdComuna` INT NOT NULL AUTO_INCREMENT,
  `IdRegion` INT NULL,
  `Descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`IdComuna`),
  INDEX `FK_Rregion_Comuna_idx` (`IdRegion` ASC) VISIBLE,
  CONSTRAINT `FK_Rregion_Comuna`
    FOREIGN KEY (`IdRegion`)
    REFERENCES `Autogestores_Warehouse`.`Region` (`IdRegion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autogestores_Warehouse`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autogestores_Warehouse`.`Ciudad` (
  `IdCiudad` INT NOT NULL AUTO_INCREMENT,
  `IdComuna` INT NULL,
  `Descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`IdCiudad`),
  INDEX `FK_CIUDAD_COMUNA_idx` (`IdComuna` ASC) VISIBLE,
  CONSTRAINT `FK_CIUDAD_COMUNA`
    FOREIGN KEY (`IdComuna`)
    REFERENCES `Autogestores_Warehouse`.`Comuna` (`IdComuna`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autogestores_Warehouse`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autogestores_Warehouse`.`Clientes` (
  `IdClientes` INT NOT NULL AUTO_INCREMENT,
  `NombreCliente` VARCHAR(255) NULL,
  `CorreoCliente` VARCHAR(255) NULL,
  `TelefonoPrimario` INT NULL,
  `TelefonoSecundario` INT NULL,
  `TelefonoOpcional` INT NULL,
  `IdCiudad` INT NULL DEFAULT 1,
  `Rut` VARCHAR(45) NULL,
  PRIMARY KEY (`IdClientes`),
  INDEX `FK_Cliente_Ciudad_idx` (`IdCiudad` ASC) VISIBLE,
  CONSTRAINT `FK_Cliente_Ciudad`
    FOREIGN KEY (`IdCiudad`)
    REFERENCES `Autogestores_Warehouse`.`Ciudad` (`IdCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autogestores_Warehouse`.`Centros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autogestores_Warehouse`.`Centros` (
  `IdCentros` INT NOT NULL AUTO_INCREMENT,
  `CodigoSAP` VARCHAR(255) NULL,
  `CodigoSIGA` VARCHAR(255) NULL,
  `IdCiudad` INT NULL,
  PRIMARY KEY (`IdCentros`),
  INDEX `FK_CENTRO_CIUDAD_idx` (`IdCiudad` ASC) VISIBLE,
  CONSTRAINT `FK_CENTRO_CIUDAD`
    FOREIGN KEY (`IdCiudad`)
    REFERENCES `Autogestores_Warehouse`.`Ciudad` (`IdCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autogestores_Warehouse`.`TipoServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autogestores_Warehouse`.`TipoServicio` (
  `IdTipoServicio` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`IdTipoServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autogestores_Warehouse`.`Plataforma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autogestores_Warehouse`.`Plataforma` (
  `IdPlataforma` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`IdPlataforma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autogestores_Warehouse`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autogestores_Warehouse`.`Usuarios` (
  `IdUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(255) NULL,
  `Correo` VARCHAR(255) NULL,
  `Password` VARCHAR(255) NULL,
  `NombreSap` VARCHAR(255) NULL,
  `NombreSiga` VARCHAR(255) NULL,
  `NombreAutofin` VARCHAR(255) NULL,
  `NombreAmicar` VARCHAR(255) NULL,
  `Activo` TINYINT NULL,
  PRIMARY KEY (`IdUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autogestores_Warehouse`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autogestores_Warehouse`.`Servicio` (
  `IdServicio` INT NOT NULL AUTO_INCREMENT,
  `IdCliente` INT NULL,
  `IdTipoServicio` INT NULL,
  `IdCentro` INT NULL,
  `FechaServicio` DATETIME NULL,
  `IdPlataformaOrigen` INT NULL,
  `IdUsuarioPropietario` INT NULL DEFAULT 1,
  PRIMARY KEY (`IdServicio`),
  INDEX `FK_TipoServicio_idx` (`IdTipoServicio` ASC) VISIBLE,
  INDEX `FK_Servicio_Cliente_idx` (`IdCliente` ASC) VISIBLE,
  INDEX `FK_Servicio_Centro_idx` (`IdCentro` ASC) VISIBLE,
  INDEX `FK_Servicio_Plataforma_idx` (`IdPlataformaOrigen` ASC) VISIBLE,
  INDEX `FK_Servicio_Usuario_idx` (`IdUsuarioPropietario` ASC) VISIBLE,
  CONSTRAINT `FK_TipoServicio`
    FOREIGN KEY (`IdTipoServicio`)
    REFERENCES `Autogestores_Warehouse`.`TipoServicio` (`IdTipoServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Servicio_Cliente`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `Autogestores_Warehouse`.`Clientes` (`IdClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Servicio_Centro`
    FOREIGN KEY (`IdCentro`)
    REFERENCES `Autogestores_Warehouse`.`Centros` (`IdCentros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Servicio_Plataforma`
    FOREIGN KEY (`IdPlataformaOrigen`)
    REFERENCES `Autogestores_Warehouse`.`Plataforma` (`IdPlataforma`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Servicio_Usuario`
    FOREIGN KEY (`IdUsuarioPropietario`)
    REFERENCES `Autogestores_Warehouse`.`Usuarios` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autogestores_Warehouse`.`ServicioVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autogestores_Warehouse`.`ServicioVenta` (
  `IdServicioVenta` INT NOT NULL AUTO_INCREMENT,
  `IdServicio` INT NOT NULL,
  `ClasePedido` VARCHAR(255) NULL,
  `Marca` VARCHAR(255) NULL,
  `Modelo` VARCHAR(255) NULL,
  `Patente` VARCHAR(45) NULL,
  `Chasis` VARCHAR(255) NULL,
  `Color` VARCHAR(45) NULL,
  `NumeroPedido` VARCHAR(45) NULL,
  `FechaPedido` DATETIME NULL,
  `NumeroFactura` VARCHAR(45) NULL,
  `FechaFactura` DATETIME NULL,
  `TipoPedido` VARCHAR(255) NULL,
  `AñoModelo` INT NULL,
  `IndCompraPara` TINYINT NULL,
  `IdClienteCompraPara` INT NULL,
  `DPS` INT NULL,
  `DPE` INT NULL,
  `PrecioLista` INT NULL,
  `PrecioCompra` INT NULL,
  `Descuentos` INT NULL,
  `Accesorios` INT NULL,
  `PrecioVenta` INT NULL,
  `CargosVehiculo` INT NULL,
  `GastosProvicionados` INT NULL,
  `Margen` INT NULL,
  `NumeroStock` VARCHAR(45) NULL,
  `CodigoVehiculo` VARCHAR(45) NULL,
  `FechaRecepcion` DATETIME NULL,
  `AutorizadoPor` VARCHAR(125) NULL,
  `InstitucionCredito` VARCHAR(255) NULL,
  `ValorCredito` INT NULL,
  `MarcaRetoma` VARCHAR(45) NULL,
  `ModeloRetoma` VARCHAR(255) NULL,
  `AñoRetoma` INT NULL,
  `ValorRetoma` INT NULL,
  `CodigoRetoma` VARCHAR(45) NULL,
  `PatenteRetoma` VARCHAR(45) NULL,
  `PagoContado` INT NULL,
  `PagoDocumentado` INT NULL,
  `PagoCreditoSimple` INT NULL,
  `PagoLeasing` INT NULL,
  `GrupoModelo` VARCHAR(255) NULL,
  `TipoUnidad` VARCHAR(255) NULL,
  `Sociedad` VARCHAR(45) NULL,
  PRIMARY KEY (`IdServicioVenta`),
  INDEX `FK_SERVICIOVENTA_SERVICIO_idx` (`IdServicio` ASC) VISIBLE,
  INDEX `FK_SERIVICIO_COMPRA_PARA_CLIENTE_idx` (`IdClienteCompraPara` ASC) VISIBLE,
  CONSTRAINT `FK_SERVICIOVENTA_SERVICIO`
    FOREIGN KEY (`IdServicio`)
    REFERENCES `Autogestores_Warehouse`.`Servicio` (`IdServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SERIVICIO_COMPRA_PARA_CLIENTE`
    FOREIGN KEY (`IdClienteCompraPara`)
    REFERENCES `Autogestores_Warehouse`.`Clientes` (`IdClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autogestores_Warehouse`.`InstitucionCredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autogestores_Warehouse`.`InstitucionCredito` (
  `IdInstitucionCredito` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`IdInstitucionCredito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autogestores_Warehouse`.`EstadoCredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autogestores_Warehouse`.`EstadoCredito` (
  `IdEstadoCredito` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`IdEstadoCredito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autogestores_Warehouse`.`ServicioCredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autogestores_Warehouse`.`ServicioCredito` (
  `IdServicioCredito` INT NOT NULL AUTO_INCREMENT,
  `IdServicio` INT NULL,
  `IdInstitucionCredito` INT NULL,
  `IdPlataforma` INT NULL,
  `Marca` VARCHAR(45) NULL,
  `Modelo` VARCHAR(255) NULL,
  `AñoModelo` INT NULL,
  `NombreProducto` VARCHAR(255) NULL,
  `EstadoAuto` VARCHAR(45) NULL,
  `Precio` INT NULL,
  `Pie` INT NULL,
  `MontoPagare` INT NULL,
  `Plazo` INT NULL,
  `SaldoPrecio` INT NULL,
  `TasaCurse` INT NULL,
  `ValorCuota` INT NULL,
  `Sueldo` INT NULL,
  `TipoVehiculo` VARCHAR(45) NULL,
  `Canal` VARCHAR(45) NULL,
  `IdEstadoCredito` INT NULL,
  PRIMARY KEY (`IdServicioCredito`),
  INDEX `FK_ServicioC_servicio_idx` (`IdServicio` ASC) VISIBLE,
  INDEX `FK_SC_CreditoInsti_idx` (`IdInstitucionCredito` ASC) VISIBLE,
  INDEX `FK_SC_Plataforma_idx` (`IdPlataforma` ASC) VISIBLE,
  INDEX `FK_SC_EstadoCredito_idx` (`IdEstadoCredito` ASC) VISIBLE,
  CONSTRAINT `FK_ServicioC_servicio`
    FOREIGN KEY (`IdServicio`)
    REFERENCES `Autogestores_Warehouse`.`Servicio` (`IdServicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SC_CreditoInsti`
    FOREIGN KEY (`IdInstitucionCredito`)
    REFERENCES `Autogestores_Warehouse`.`InstitucionCredito` (`IdInstitucionCredito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SC_Plataforma`
    FOREIGN KEY (`IdPlataforma`)
    REFERENCES `Autogestores_Warehouse`.`Plataforma` (`IdPlataforma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_SC_EstadoCredito`
    FOREIGN KEY (`IdEstadoCredito`)
    REFERENCES `Autogestores_Warehouse`.`EstadoCredito` (`IdEstadoCredito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autogestores_Warehouse`.`TipoLista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autogestores_Warehouse`.`TipoLista` (
  `IdTipoLista` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`IdTipoLista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autogestores_Warehouse`.`ListaClientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autogestores_Warehouse`.`ListaClientes` (
  `IdListaCliente` INT NOT NULL AUTO_INCREMENT,
  `IdPropietario` INT NULL,
  `Descripcion` TEXT NULL,
  `Activa` TINYINT NULL,
  `Editable` TINYINT NULL,
  `FechaCreacion` DATETIME NULL,
  `IdTipoLista` INT NULL,
  PRIMARY KEY (`IdListaCliente`),
  INDEX `FK_LISTA_CLIENTES_TIPO_LISTA_idx` (`IdTipoLista` ASC) VISIBLE,
  INDEX `FK_LISTA_CLIENTES_USUARIOS_idx` (`IdPropietario` ASC) VISIBLE,
  CONSTRAINT `FK_LISTA_CLIENTES_TIPO_LISTA`
    FOREIGN KEY (`IdTipoLista`)
    REFERENCES `Autogestores_Warehouse`.`TipoLista` (`IdTipoLista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_LISTA_CLIENTES_USUARIOS`
    FOREIGN KEY (`IdPropietario`)
    REFERENCES `Autogestores_Warehouse`.`Usuarios` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Autogestores_Warehouse`.`DetalleListaCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Autogestores_Warehouse`.`DetalleListaCliente` (
  `IdDetalleListaCliente` INT NOT NULL AUTO_INCREMENT,
  `IdListaCliente` INT NULL,
  `IdPropietario` INT NULL,
  `IdCliente` INT NULL,
  `FechaIngreso` DATETIME NULL,
  `FechaActualizacion` DATETIME NULL,
  PRIMARY KEY (`IdDetalleListaCliente`),
  INDEX `FK_Detalle_Lista_idx` (`IdListaCliente` ASC) VISIBLE,
  INDEX `FK_Detalle_Propietario_idx` (`IdPropietario` ASC) VISIBLE,
  INDEX `FK_Detalle_Cliente_idx` (`IdCliente` ASC) VISIBLE,
  CONSTRAINT `FK_Detalle_Lista`
    FOREIGN KEY (`IdListaCliente`)
    REFERENCES `Autogestores_Warehouse`.`ListaClientes` (`IdListaCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Detalle_Propietario`
    FOREIGN KEY (`IdPropietario`)
    REFERENCES `Autogestores_Warehouse`.`Usuarios` (`IdUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Detalle_Cliente`
    FOREIGN KEY (`IdCliente`)
    REFERENCES `Autogestores_Warehouse`.`Clientes` (`IdClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Autogestores_Warehouse`.`Region`
-- -----------------------------------------------------
START TRANSACTION;
USE `Autogestores_Warehouse`;
INSERT INTO `Autogestores_Warehouse`.`Region` (`IdRegion`, `Descripcion`) VALUES (1, 'SIN REGIÓN');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Autogestores_Warehouse`.`Comuna`
-- -----------------------------------------------------
START TRANSACTION;
USE `Autogestores_Warehouse`;
INSERT INTO `Autogestores_Warehouse`.`Comuna` (`IdComuna`, `IdRegion`, `Descripcion`) VALUES (1, 1, 'SIN COMUNA');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Autogestores_Warehouse`.`Ciudad`
-- -----------------------------------------------------
START TRANSACTION;
USE `Autogestores_Warehouse`;
INSERT INTO `Autogestores_Warehouse`.`Ciudad` (`IdCiudad`, `IdComuna`, `Descripcion`) VALUES (1, 1, 'SIN CIUDAD');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Autogestores_Warehouse`.`TipoServicio`
-- -----------------------------------------------------
START TRANSACTION;
USE `Autogestores_Warehouse`;
INSERT INTO `Autogestores_Warehouse`.`TipoServicio` (`IdTipoServicio`, `Descripcion`) VALUES (1, 'Venta Nuevos');
INSERT INTO `Autogestores_Warehouse`.`TipoServicio` (`IdTipoServicio`, `Descripcion`) VALUES (2, 'Venta Usados');
INSERT INTO `Autogestores_Warehouse`.`TipoServicio` (`IdTipoServicio`, `Descripcion`) VALUES (3, 'Postventa');
INSERT INTO `Autogestores_Warehouse`.`TipoServicio` (`IdTipoServicio`, `Descripcion`) VALUES (4, 'Lead Nuevos');
INSERT INTO `Autogestores_Warehouse`.`TipoServicio` (`IdTipoServicio`, `Descripcion`) VALUES (5, 'Lead Usados');
INSERT INTO `Autogestores_Warehouse`.`TipoServicio` (`IdTipoServicio`, `Descripcion`) VALUES (6, 'Creditos Nuevos');
INSERT INTO `Autogestores_Warehouse`.`TipoServicio` (`IdTipoServicio`, `Descripcion`) VALUES (7, 'Creditos Usados');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Autogestores_Warehouse`.`Usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `Autogestores_Warehouse`;
INSERT INTO `Autogestores_Warehouse`.`Usuarios` (`IdUsuario`, `Nombre`, `Correo`, `Password`, `NombreSap`, `NombreSiga`, `NombreAutofin`, `NombreAmicar`, `Activo`) VALUES (1, 'SIN ASIGNAR', 'SINASIGNAR', '4df857gf6a44f6a4f69ae4f655d4f6454as4f8ase4f654asd4f6', 'SIN ASIGNAR', 'SIN ASIGNAR', 'SIN ASIGNAR', 'SIN ASIGNAR', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `Autogestores_Warehouse`.`EstadoCredito`
-- -----------------------------------------------------
START TRANSACTION;
USE `Autogestores_Warehouse`;
INSERT INTO `Autogestores_Warehouse`.`EstadoCredito` (`IdEstadoCredito`, `Descripcion`) VALUES (1, 'Aprobada');
INSERT INTO `Autogestores_Warehouse`.`EstadoCredito` (`IdEstadoCredito`, `Descripcion`) VALUES (2, 'Rechazado');
INSERT INTO `Autogestores_Warehouse`.`EstadoCredito` (`IdEstadoCredito`, `Descripcion`) VALUES (3, 'Otorgada');
INSERT INTO `Autogestores_Warehouse`.`EstadoCredito` (`IdEstadoCredito`, `Descripcion`) VALUES (4, 'Solicitud');
INSERT INTO `Autogestores_Warehouse`.`EstadoCredito` (`IdEstadoCredito`, `Descripcion`) VALUES (5, 'Cotización');
INSERT INTO `Autogestores_Warehouse`.`EstadoCredito` (`IdEstadoCredito`, `Descripcion`) VALUES (6, 'Devuelto');
INSERT INTO `Autogestores_Warehouse`.`EstadoCredito` (`IdEstadoCredito`, `Descripcion`) VALUES (7, 'Cursado');
INSERT INTO `Autogestores_Warehouse`.`EstadoCredito` (`IdEstadoCredito`, `Descripcion`) VALUES (8, 'Pre-Curse');
INSERT INTO `Autogestores_Warehouse`.`EstadoCredito` (`IdEstadoCredito`, `Descripcion`) VALUES (9, 'Condicionado');
INSERT INTO `Autogestores_Warehouse`.`EstadoCredito` (`IdEstadoCredito`, `Descripcion`) VALUES (10, 'RevisionFirma');
INSERT INTO `Autogestores_Warehouse`.`EstadoCredito` (`IdEstadoCredito`, `Descripcion`) VALUES (11, 'Anulado');
INSERT INTO `Autogestores_Warehouse`.`EstadoCredito` (`IdEstadoCredito`, `Descripcion`) VALUES (12, 'Evaluación');

COMMIT;

